name: ${project.name}
main: wtf.choco.artifice.Artifice
version: ${project.version}
description: Mystical relics and obelisks to make your server more magical
author: Choco
api-version: 1.15

commands:
    artifice:
      description: The main administrative command for relics
      usage: /<command> <reload|version>
    artifact:
      description: The artifact command for artifact manipulation
      usage: /<command> <list|give>